---
name: ESLint (JS/TS) Action

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  eslint:
    name: eslint
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: install node v23
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 23
      - name: yarn install
        run: yarn install
      - name: eslint
        uses: icrawl/action-eslint@v1
